# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UseNode@1
  inputs:
    checkLatest: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.defaultWorkingDirectory)'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.defaultWorkingDirectory)'
    customCommand: 'test'

    # Starter pipeline
- task: PublishTestResults@2
  inputs:
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testResultsFormat: 'JUnit'
    testResultsFiles: 'wdio-0-0-junit-reporter.xml'
    condition: always()
    